### ISSUE TITLE
where is skydb instance 

### ISSUE THREAD

**Issue by v1xingyue** [SkynetLabs/nodejs-skynet#1]
It seems that browser-js has skydb object . But node-js sdk does not exits . Anyway I can use skydb instance in this sdk code .

**Comment by m-cat** [comment]
Sorry, I just realized I didn't have notifications enabled for this repo. SkyDB is not implemented in the Node SDK because of lack of developer resources. We do plan on making a JS SDK that is isomorphic and have active plans for that. This repo will be archived after that.
