### ISSUE TITLE
Integrate some of the Skydb functions! Most things are ok! Please

### ISSUE THREAD

**Issue by parajbs** [SkynetLabs/nodejs-skynet#129]
**Hello developers,**

Can you integrate **skydb**? At least for testing!!
And me with the problem with the **"new File()"** command, which only works in the browser!
I've already tested the functions:

**OK is:**
- getJSON
- deleteJSON

**Defect is:**
-setJSON

**Remaining functions from skydb not tested yet!**
- getRawBytes
- getEntryData
- setEntryData
- deleteEntryData

###########

Now to integrate the functions that already work in src/client.js:

**OLD lines 54-57:**
    // SkyDB
    this.db = {
      setDataLink: browserClient.db.setDataLink.bind(browserClient),
    };

**NEW:**
    // SkyDB
    this.db = {
      setDataLink: browserClient.db.setDataLink.bind(browserClient),
      deleteJSON: browserClient.db.deleteJSON.bind(browserClient),
      getJSON: browserClient.db.getJSON.bind(browserClient),
// From here defect or untested, so commented
// setJSON: browserClient.db.setJSON.bind(browserClient),
// getRawBytes: browserClient.db.getRawBytes.bind(browserClient),
// getEntryData: browserClient.db.getEntryData.bind(browserClient),
// setEntryData: browserClient.db.setEntryData.bind(browserClient),
// deleteEntryData: browserClient.db.deleteEntryData.bind(browserClient),
    };

  **###########**

Here is the error with the db.setJSON command:
When using setJSON, the error comes in src skydb.ts in the **"getOrCreateRegistryEntry"** function:
**In line 526:**
const file = new File([JSON.stringify(fullData)], `dk:${dataKeyHex}`, { type: "application/json" });

**The **"new File()"** command is only available in the browser and not in nodejs!!!!**

I couldn't find any other errors about db.setJSON because I don't know exactly how to fix the first error!

The error with "new File()" also occurs in the **"getOrCreateRawBytesRegistryEntry"** function!

thanks for your help

**Comment by parajbs** [comment]
Very important !!!

**Please, please, please only integrate getJSON only!**
It's just a line in your code!
**I've already tested it and claps great without mistake!**

It is important to be able to answer the DATA correctly and compatible from Skydb!

I find it very important for the compatibility of the "nodejs-skynet" version to "skynet-js" version!

Please integrate these a line in **src/client.js**:

**getJSON: browserClient.db.getJSON.bind (browserClient),**


New:
     **// SKYDB**
     this.db = {
       setDalink: browserClient.db.setDatalink.bind (browserClient),
       **getJSON: browserClient.db.getJSON.bind (browserClient),**
     };****


Please help

**Comment by m-cat** [comment]
Hi, what is your use case for wanting `getJSON` without `setJSON`? As you are aware, `setJSON` only works in browser contexts and due to a shortage of developer resources, it is unlikely that we will re-implement SkyDB for NodeJS.

**Comment by parajbs** [comment]
hello m-cup,

I find it **very unfortunate**!
I'm currently working on the projects "Fluffy9/Zenbase" / "SkynetLabs/gundb-relay" and "SkynetLabs/gundb-adapter"!
 
In "Fluffy9/Zenbase" "setJSON" and "getJSON" are used!
The data format that skydb stores on skynet looks like this:

**{"_data":{"example": "This is some example JSON Data."},"_v":2}**

For the nodejs-version has the gituser "dghelm" rewritten a few functions to replace "setJSON" and "getJSON"! It still uses skydb's "setDataLink" function though!
But the data format that is stored looks like this:

**{"example": "This is some example JSON Data."}**

Then I looked for the error and took a closer look at "SkynetLabs/nodejs-skynet" and integrated all the functions of skydb to see exactly where the error happened!
**I noticed that some of skydb's functions (e.g. getJSON, etc) work very cleanly!**
The error always occurred when **"new File"** was used, e.g. with the "setJSON" function!

**Then I saw that skydb stores the data in a certain format on skynet!
I only noticed this because I had integrated "getJSON"!!!**

My reason for requesting the integration of "getJSON" is first of all for the further development of and the integration of working functions of "skynet-js"!

And I thought, since the gituser "dghelm" bypassed the "setJSON" function in a different way, you could use it to rewrite a new "setJSON" for "SkynetLabs/nodejs-skynet" and thus you could later integrate skydb completely!
**Would be cool! Or not?**

So my request was for development reasons!

**Comment by parajbs** [comment]
**Hello m-cut**

Are you interested in my solution of **"db.setJSON"** which I made from your code from **"uploadData"** / part from function **"store.put" from "SkynetLabs/gundb-adapter"** / my own code for implementation in **"src/clients.js"** and **for compatibility with skydb!**
"db.getJSON" / "db.deleteJSON" is also integrated!

I installed the solution on my test server and it's running! Everything great with no problems!

If you are interested then post it on github and you can check it out and test it !!??!!??
  
**Request for feedback**

**Comment by m-cat** [comment]
I would be happy to review your code if you raised a PR! We would just need to have some tests in the repository to make sure it works correctly.

**Comment by parajbs** [comment]
hello m-cat,

I'm about to do a PR, but I'm just out to eat! But after that!

Since yesterday I've been trying to integrate the new functions "**dbV2.setJSON**" and "**dbV2.getJSON**"!
New "dbV2" isn't ready yet, so I'll definitely leave it out of the PR!

Should I create a PR using only the db.setJSON and db.getJSON functions?

Or all skydb functions (e.g. deleteJSON, etc.)?

**Comment by m-cat** [comment]
Implement as much as you feel like! I'm sure many others would find your contribution useful.

**Comment by parajbs** [comment]
My repo is from the "in-memory-upload" branch and my PR is also intended and created for the "in-memory-upload" branch!!!!

here the PR:
https://github.com/SkynetLabs/nodejs-skynet/pull/140

or my repo:
https://github.com/parajbs/nodejs-skynet/tree/skydb-integration-test1

I only activated these functions once:
- "db.setJSON"
- "db.getJSON"
- "db.deleteJSON"

These functions are **commented out** because I **haven't fully tested** them yet, but they are ok:
- // "db.getEntryData"
- // "db.setEntryData"
- // "deleteEntryData"
- // "db.getRawBytes"

With the **new "dbV2"** mySky is in play, which is causing me problems at the moment!
But even with "mySky" it could work in a roundabout way, but I'm not quite sure yet! ? ! ? !

**Comment by parajbs** [comment]
hello m-cat

I have my extra repo from the branch "in-memory-upload" because there are also their "uploadData" and "downloadData" functions, which I find just as interesting and important!

In my opinion, they should also be integrated in "skynet-js", then it would also be easier in the nodejs version!

**Comment by parajbs** [comment]
hello m-cat

Can you take a look at **"skydb.js"**, I think this one with the
**"SkydbFormatedData"** could be solved differently!
The only very important thing is that "data" in the browser needs a "json object" for the "db.setJSON" function of "skynet-js", and that's why I used "JSON.stringify(data)" here in nodejs!

maybe you can use a function of "skynet-js" directly for data compatibility? I haven't checked yet!

**Comment by m-cat** [comment]
> hello m-cat
> 
> I have my extra repo from the branch "in-memory-upload" because there are also their "uploadData" and "downloadData" functions, which I find just as interesting and important!
> 
> In my opinion, they should also be integrated in "skynet-js", then it would also be easier in the nodejs version!

Done!

https://github.com/SkynetLabs/nodejs-skynet/pull/141

**Comment by parajbs** [comment]
Hello m-cat

I have just cleded "SkynetLabs/nodejs-skynet".
Next I changed the version to "4.1.0" in "package.json", and "yarn test".
All tests run clean. Great.

After that, in "package.json" I changed the version to "4.2.0-beta" because I have the "client.getFileContentBinary" and "client.getFileContentBinaryHns" still wanted to integrate in "SkynetLabs/nodejs-skynet".

I tested "scripts/skydb.js" and "scripts/skydb_v2.js", and everything ok.
Then I executed "Yarn Test".
And there are many errors.

Everywhere the same error from version "4.2.0-beta" upwards:
`Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'`

What's going on there?
I haven't changed anything on the code, just the "package.json"!

Hopefully you can help me find out the problem.



Here are the complete errors:
```
  ● SkyDB V1 › db.setDataLink › should be a dataLink set

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      29 |   describe("db.setDataLink", () => {
      30 |     it("should be a dataLink set", async () => {
    > 31 |       await client.db.setDataLink(privateKey, dataKey, dataLink);
         |       ^
      32 |     });
      33 |   });
      34 |

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getNextRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:337:25)
      at SkynetClient.setEntryData (node_modules/skynet-js/dist/cjs/skydb.js:194:19)
      at SkynetClient.setDataLink (node_modules/skynet-js/dist/cjs/skydb.js:140:5)
      at Object.<anonymous> (src/skydb.test.js:31:7)

  ● SkyDB V1 › db.setEntryData › should set entryData

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      35 |   describe("db.setEntryData", () => {
      36 |     it("should set entryData", async () => {
    > 37 |       const receivedData = await client.db.setEntryData(privateKey, dataKey, rawEntryData);
         |                            ^
      38 |
      39 |       await expect(receivedData["data"]).toEqual(rawEntryData);
      40 |     });

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getNextRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:337:25)
      at SkynetClient.setEntryData (node_modules/skynet-js/dist/cjs/skydb.js:194:19)
      at Object.<anonymous> (src/skydb.test.js:37:28)

  ● SkyDB V1 › db.getEntryData › should get entryData

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      43 |   describe("db.getEntryData", () => {
      44 |     it("should get entryData", async () => {
    > 45 |       const receivedData = await client.db.getEntryData(publicKey, dataKey);
         |                            ^
      46 |
      47 |       await expect(receivedData["data"]).toEqual(rawEntryData);
      48 |     });

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:429:23)
      at SkynetClient.getEntryData (node_modules/skynet-js/dist/cjs/skydb.js:162:19)
      at Object.<anonymous> (src/skydb.test.js:45:28)

  ● SkyDB V1 › db.getRawBytes › should get rawBytes

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      51 |   describe("db.getRawBytes", () => {
      52 |     it("should get rawBytes", async () => {
    > 53 |       const receivedData = await client.db.getRawBytes(publicKey, dataKey);
         |                            ^
      54 |
      55 |       await expect(formatSkylink(receivedData["dataLink"])).toEqual(dataLink);
      56 |       await expect("[" + receivedData["data"] + "]").toEqual(rawBytesData);

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:429:23)
      at SkynetClient.getRawBytes (node_modules/skynet-js/dist/cjs/skydb.js:246:19)
      at Object.<anonymous> (src/skydb.test.js:53:28)

  ● SkyDB V1 › db.setJSON › should set jsonData to skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      59 |
      60 |   // Fetch the current value to find out the revision.
    > 61 |   const signedEntry = await client.registry.getEntry(publicKey, dataKey, DEFAULT_GET_ENTRY_OPTIONS);
         |                       ^
      62 |
      63 |   const revision = getNextRevisionFromEntry(signedEntry.entry);
      64 |

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getOrCreateRegistryEntry (src/skydb.js:61:23)
      at SkynetClient.setJSONdbV1 (src/skydb.js:31:31)
      at Object.<anonymous> (src/skydb.test.js:62:28)

  ● SkyDB V1 › db.getJSON › should get jsonData from skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      68 |   describe("db.getJSON", () => {
      69 |     it("should get jsonData from skydb", async () => {
    > 70 |       const receivedData = await client.db.getJSON(publicKey, dataKey);
         |                            ^
      71 |
      72 |       await expect(receivedData.data).toEqual(data);
      73 |     });

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:429:23)
      at SkynetClient.getJSON (node_modules/skynet-js/dist/cjs/skydb.js:44:19)
      at Object.<anonymous> (src/skydb.test.js:70:28)

  ● SkyDB V1 › db.deleteJSON › should delete jsonData on skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      76 |   describe("db.deleteJSON", () => {
      77 |     it("should delete jsonData on skydb", async () => {
    > 78 |       await client.db.deleteJSON(privateKey, dataKey);
         |       ^
      79 |       const receivedData = await client.db.getJSON(publicKey, dataKey);
      80 |
      81 |       await expect(receivedData.data).toEqual(null);

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getNextRegistryEntry (node_modules/skynet-js/dist/cjs/skydb.js:337:25)
      at SkynetClient.setEntryData (node_modules/skynet-js/dist/cjs/skydb.js:194:19)
      at SkynetClient.deleteJSON (node_modules/skynet-js/dist/cjs/skydb.js:119:5)
      at Object.<anonymous> (src/skydb.test.js:78:7)

 FAIL  src/skydb_v2.test.js
  ● SkyDB V2 › dbV2.getJSON › should get jsonData from skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntryAndUpdateCache (node_modules/skynet-js/dist/cjs/skydb_v2.js:473:23)
      at node_modules/skynet-js/dist/cjs/skydb_v2.js:91:23

  ● SkyDB V2 › dbV2.getJSON › should get jsonData from skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntryAndUpdateCache (node_modules/skynet-js/dist/cjs/skydb_v2.js:473:23)
      at node_modules/skynet-js/dist/cjs/skydb_v2.js:91:23

  ● SkyDB V2 › dbV2.getEntryData › should get entryData

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntryAndUpdateCache (node_modules/skynet-js/dist/cjs/skydb_v2.js:473:23)
      at node_modules/skynet-js/dist/cjs/skydb_v2.js:229:23

  ● SkyDB V2 › dbV2.getRawBytes › should get rawBytes

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntryAndUpdateCache (node_modules/skynet-js/dist/cjs/skydb_v2.js:473:23)
      at node_modules/skynet-js/dist/cjs/skydb_v2.js:329:23

  ● SkyDB V2 › dbV2.deleteJSON › should delete jsonData on skydb

    Did not get a complete entry response despite a successful request. Please try again and report this issue to the devs if it persists. Error: Error: Expected entry response field 'response.data.data' to be type 'string', was type 'undefined'

      at SkynetClient.getEntry (node_modules/skynet-js/dist/cjs/registry.js:102:15)
      at getSkyDBRegistryEntryAndUpdateCache (node_modules/skynet-js/dist/cjs/skydb_v2.js:473:23)
      at node_modules/skynet-js/dist/cjs/skydb_v2.js:91:23

```

**Comment by m-cat** [comment]
Hi @parajbs, unfortunately our portals are a bit unstable, especially our default portal `https://siasky.net`. Please let me know if the issue persists.

**Comment by m-cat** [comment]
Closing as SkyDB is now integrated. Please open a new issue if the network problems persist.
