### ISSUE TITLE
issue on "download" with parameter { path: "dir2/file3" }

### ISSUE THREAD

**Issue by parajbs** [SkynetLabs/nodejs-skynet#175]
hello **m-cat,**

I've been working on a CLI for skynet based on "nodejs-skynet" for a few days, while testing and looking through the sdk doc on "sdk.skynetlabs.com" **I noticed a problem in the "download function".**

In the "nodejs version" of the doc:
https://sdk.skynetlabs.com/?javascript--node#downloading-a-file-from-an-uploaded-directory

```
// Using the path option.
(async() => {
  const skylink = "XABvi7JtJbQSMAcDwnUnmp2FKDPjg8_tTTFP4BwMSxVdEg";
    await client.downloadFile("./dst.jpg", skylink, { path: "dir2/file3" });
    console.log('Download successful');
})()
```

I tested it but it doesn't recognize the parameter "{ path: "dir2/file3" }".
If I attach the path to skylink at the back, it works and it's OK.

I've checked the code to see if I can include it. didn't manage it.
Maybe you can take a look and see if you can do it.

If not, we should correct the sdk-doc (see link above), and remove for "nodejs version".

Since I'm trying to integrate all functions of "nodejs-skynet" into the CLI, I may find other errors or problems that I wasn't aware of before.
**I will contact you.
I only noticed the error because I use the sdk-doc for testing.**

**Comment by m-cat** [comment]
Thanks for reporting! I've fixed the live docs already.

**Comment by parajbs** [comment]
Hello **m-cat,**

I think yesterday I noticed another important error or I don't understand why it doesn't work.

I wanted to start an upload to "skynetfree.net" with a key, but I noticed in the sdk doc on "sdk.skynetlabs.com" that there are three different versions.

First version **"SkynetAPIKey"**:
https://sdk.skynetlabs.com/#setting-connection-options

```
const client = new SkynetClient("", { SkynetApiKey: "foobar" });
```

Second version **"skynetAPIKey"**:
https://sdk.skynetlabs.com/#skynet-portal-authentication

`    const skylink = await client.uploadFile("./image.jpg", { skynetAPIKey: "foobar" });`

Third version **"APIKey"**:
https://sdk.skynetlabs.com/#local-node-authentication

`   const skylink = await client.uploadFile("./image.jpg", { APIKey: "foobar", customUserAgent: "Sia-Agent" });`


When testing, I only got the second version to work, where "skynetAPIKey" is written at the beginning of the "s" in lower case.

I couldn't test the third version because I don't have any locale skynet instances.

Is the first version, where "SkynetAPIKey" is capitalized at the beginning with the "S", a bug??????
If not, can you explain to me why you need them.

**Comment by parajbs** [comment]
Hello m-cat,

Sorry, I think I just found a little bug in "uploading-a-directory". I think the console.log should also contain "skylink" instead of "url", since skynet returns a skylink and not a url.
https://sdk.skynetlabs.com/?javascript--node#uploading-a-directory
 
    const url = await client.uploadDirectory("./images");
    console.log(`Upload successful, url: ${url}`);

It's not a big bug, but misleading, because you copy the code from the sdk-doc to test it.

**Comment by parajbs** [comment]
Hello m-cat,

Yes, you are right.
It's an error in my new CLI app, I've already found it, will correct it later and test it.

Thank you for clarifying "skynetApiKey". Use it from now on.
