### ISSUE TITLE
When I upload larger files, I often get an error message.

### ISSUE THREAD

**Issue by parajbs** [SkynetLabs/nodejs-skynet#182]
Hello m-cat,

When I upload larger files, I often get an error message with the "uploadFile" function:

```
Error: SkynetMaxUploadSize header is missing
    at Object.onError (D:\w4\2\3\nodejs-skynet\src\upload.js:86:32)
    at Upload._emitError (D:\w4\2\3\nodejs-skynet\node_modules\@skynetlabs\tus-js-client\lib.es5\upload.js:670:22)
    at Upload._emitHttpError (D:\w4\2\3\nodejs-skynet\node_modules\@skynetlabs\tus-js-client\lib.es5\upload.js:639:12)
    at D:\w4\2\3\nodejs-skynet\node_modules\@skynetlabs\tus-js-client\lib.es5\upload.js:772:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

And since today only this error when uploading larger files (41MB-55MB).

I don't understand the error. I think it might be a problem in the "tus-js-client" but I'm not sure.
Yesterday I still thought the error would come from the portal, because occasionally it worked with the same file.

But today it didn't work anymore, the same file (41MB large).

**Comment by parajbs** [comment]
Hello **m-cat,**

I've been trying to figure out the error for the past 4 hours.

I noticed that **only every 20 attempts to upload a file with a size of 45MB works**.

A smaller file with **27MB size always works** when uploading.

I also noticed that the problem is currently only happening on the "https://siasky.net" portal.
There is no error on the proral "https://web3portal.com", but it is very very slow.

So I think it's the "siasky.net" portal.
I just don't understand why it works from time to time, and often not.

**Comment by parajbs** [comment]
Hello m-cat,

I just did another test in the browser with "skynet-js" trying to upload a file with 78MB size to "https://siasky.net", but it doesn't work.

The same error comes up, but more info:

```
File {name: 'session-desktop-win-1.8.6.exe', lastModified: 1655693782235, lastModifiedDate: Mon Jun 20 2022 04:56:22 GMT+0200 (Mitteleuropäische Sommerzeit), webkitRelativePath: '', size: 78482296, …}
lastModified: 1655693782235
lastModifiedDate: Mon Jun 20 2022 04:56:22 GMT+0200 (Mitteleuropäische Sommerzeit) {}
name: "session-desktop-win-1.8.6.exe"
size: 78482296
type: "application/x-msdownload"
webkitRelativePath: ""
[[Prototype]]: File
```

`XHR finished loading: OPTIONS "https://siasky.net/skynet/tus".`

`POST https://siasky.net/skynet/tus 400`

`XHR failed loading: POST "https://siasky.net/skynet/tus".`

`POST https://siasky.net/skynet/tus 400`

`XHR failed loading: POST "https://siasky.net/skynet/tus".
`

```
Uncaught (in promise) Error: SkynetMaxUploadSize header is missing
    at Object.onError (index.js:17118:40)
    at Upload._emitError (index.js:1812:22)
    at index.js:1662:16

```

**Comment by m-cat** [comment]
Thanks for the report, we'll look into it. Apologies for the inconvenience.

> I also noticed that the problem is currently only happening on the "[siasky.net](https://siasky.net/)" portal.
There is no error on the proral "[web3portal.com](https://web3portal.com/)", but it is very very slow.

You can try `skynetfree.net` for now. Note that you'll need to make an account and use an API key to upload:

https://docs.skynetlabs.com/skynet-topics/portal-accounts/api-and-sponsor-keys

**Comment by parajbs** [comment]
Hello m-cat,

I just tested uploading small files (1MB-15MB) and large files (45MB-78MB) to "skynetfree.net" with "skynetApiKey".

**With the small files (1MB-15MB) everything works great.**

With large files (45MB-78MB) this error occurs:


```
Error: <!DOCTYPE html>
<html class="h-full">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- meta tags generated with https://metatags.io/ -->
    <title>401: Unauthorized</title>
    <meta name="title" content="401: Unauthorized" />
    <meta
      name="description"
      content="You must be authenticated to access this content"
    />
    <!-- svg favicon encoded with https://yoksel.github.io/url-encoder/ -->
    <link
      rel="icon"
      href="data:image/svg+xml, %3Csvg role='img' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg' fill='%2300C65E' %3E%3Ctitle%3ESkynet%3C/title%3E%3Cpath d='m-.0004 6.4602 21.3893 11.297c.561.2935.6633 1.0532.1999 1.4846h-.011a10.0399 10.0399 0 0 1-2.2335 1.5307c-6.912 3.4734-14.9917-1.838-14.5438-9.5605l2.8601 1.9752c.856 4.508 5.6187 7.1094 9.8742 5.3932zm8.6477 3.1509 14.3661 5.6785a.8704.8704 0 0 1 .5197 1.0466v.0182c-.1537.5377-.7668.7938-1.2575.5252zm5.2896-7.4375c2.7093-.2325 6.0946.7869 8.1116 3.3871 1.699 2.1951 2.0497 4.8772 1.9298 7.6465v-.007c-.0478.5874-.6494.9616-1.1975.745l-9.7652-3.8596 9.0656 2.4313a7.296 7.296 0 0 0-1.0677-4.5631c-2.9683-4.7678-9.9847-4.5344-12.6297.4201a7.5048 7.5048 0 0 0-.398.8831L5.5546 7.9614c.069-.1017.1417-.198.2144-.2962.1163-.2416.2417-.487.3798-.7268 1.6118-2.7911 4.3102-4.4338 7.1558-4.6973.2108-.0182.4215-.049.6323-.0672z' /%3E%3C/svg%3E"
      type="image/svg+xml"
    />
    <!-- https://fonts.google.com/specimen/Sora -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Sora:wght@400;800&display=swap"
      rel="stylesheet"
    />
    <!-- https://tailwindcss.com/docs/installation/play-cdn -->
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
      tailwind.config = {
        theme: { extend: { fontFamily: { sans: ["Sora", "sans-serif"] } } },
      };
    </script>
  </head>
  <body class="h-full">
    <div
      class="bg-white min-h-full px-4 py-16 sm:px-6 sm:py-24 md:grid md:place-items-center lg:px-8"
    >
      <div class="max-w-max mx-auto">
        <main class="sm:flex">
          <svg
            role="img"
            viewBox="0 0 24 24"
            xmlns="http://www.w3.org/2000/svg"
            height="88"
            fill="#00C65E"
          >
            <title>Skynet</title>
            <path
              d="m-.0004 6.4602 21.3893 11.297c.561.2935.6633 1.0532.1999 1.4846h-.011a10.0399 10.0399 0 0 1-2.2335 1.5307c-6.912 3.4734-14.9917-1.838-14.5438-9.5605l2.8601 1.9752c.856 4.508 5.6187 7.1094 9.8742 5.3932zm8.6477 3.1509 14.3661 5.6785a.8704.8704 0 0 1 .5197 1.0466v.0182c-.1537.5377-.7668.7938-1.2575.5252zm5.2896-7.4375c2.7093-.2325 6.0946.7869 8.1116 3.3871 1.699 2.1951 2.0497 4.8772 1.9298 7.6465v-.007c-.0478.5874-.6494.9616-1.1975.745l-9.7652-3.8596 9.0656 2.4313a7.296 7.296 0 0 0-1.0677-4.5631c-2.9683-4.7678-9.9847-4.5344-12.6297.4201a7.5048 7.5048 0 0 0-.398.8831L5.5546 7.9614c.069-.1017.1417-.198.2144-.2962.1163-.2416.2417-.487.3798-.7268 1.6118-2.7911 4.3102-4.4338 7.1558-4.6973.2108-.0182.4215-.049.6323-.0672z"
            />
          </svg>
          <div class="sm:ml-6">
            <div class="sm:border-l sm:border-gray-200 sm:pl-6">
              <h1
                class="text-xl font-extrabold text-gray-900 tracking-tight sm:text-2xl"
              >
                You must be authenticated to access this content
              </h1>
              <p class="mt-1 text-base text-gray-500">
                You're being redirected to the Log In page of this Skynet Portal
              </p>
              <p class="mt-2 text-sm text-gray-300">HTTP 401: Unauthorized</p>
            </div>
            <div
              class="mt-10 flex space-x-3 sm:border-l sm:border-transparent sm:pl-6"
            >
              <p class="mt-1 text-sm text-gray-500">
                If you're not redirected automatically,
                <a
                  href="https://account.skynetfree.net/auth/login"
                  class="text-[#00C65E]"
                  id="login-btn"
                  >click here</a
                >.
              </p>
            </div>
          </div>
        </main>
      </div>
    </div>
    <script>
      const encodedReturnTo = encodeURIComponent(window.location.href);
      const portalLoginUrl = `https://account.skynetfree.net/auth/login?return_to=${encodedReturnTo}`

      // add return_to url to click here button
      document.getElementById("login-btn").href = portalLoginUrl;

      // prevent auto redirect if not on portal domain to allow local development
      if (window.location.hostname.endsWith("skynetfree.net")) {
        setTimeout(function redirect() {
          const encodedReturnTo = encodeURIComponent(window.location.href);
          window.location.href = portalLoginUrl;
        }, 5000); // redirect after 5 seconds
      }
    </script>
  </body>
</html>
    at Object.onError (D:\w4\2\3\nodejs-skynet\src\upload.js:86:32)
    at Upload._emitError (D:\w4\2\3\nodejs-skynet\node_modules\@skynetlabs\tus-js-client\lib.es5\upload.js:670:22)
    at Upload._emitHttpError (D:\w4\2\3\nodejs-skynet\node_modules\@skynetlabs\tus-js-client\lib.es5\upload.js:639:12)
    at D:\w4\2\3\nodejs-skynet\node_modules\@skynetlabs\tus-js-client\lib.es5\upload.js:772:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```
At the moment it only works on the portal "https://web3portal.com/" without "skynetApiKey"
upload large files (45MB-78MB).

**Comment by parajbs** [comment]
Hello **m-cat,**

**Sorry for the huge text.
I hope you understand everything.**

It's good that I made an error in the browser during the test, because otherwise I wouldn't have noticed the difference.
I accidentally tested "skynet-js" with version 4.1, where the error message "SkynetMaxUploadSize header is missing" comes up

When I then tried the same test again with 4.3 "skynet-js", everything worked.
The same tests in the browser with 4.1 and 4.3 "skynet-js" with the portal "https://web3portal.com" work great.

The tests with the "master" from "skynet-nodejs" work great with the portal "https://web3portal.com".

In the same tests with the "https://siasky.net" portal and the "master" version of "skynet-nodejs", the error message "SkynetMaxUploadSize header is missing" appears again.


**Browsing through the code, I noticed:**
The "uploadFile" and "uploadLargeFile" functions have changed a bit in "skynet-js" and since in "skynet-nodejs" the code from the "uploadData" function more closely matches the code of version 4.1 "skynet-js".

So I think the portal "https://siasky.net" works with the latest version 4.3 of "skynet-js" and the latest 2.4.1 "tus-js-client".
Which leads to the error message "SkynetMaxUploadSize header is missing".

And with the portal "https://web3portal.com" I think that you are working with version 4.1 of "skynet-js" and the latest 2.3.0 "tus-js-client".
Therefore all tests work in the browser with 4.1 and 4.3 of "skynet-js".

The "skynet-nodejs" version also works, because the code of the "uploadData" function rather matches the code of the 4.1 "skynet-js" version, and the portal definitely uses "skynet-js" 4.1.

**I think we should find the solution to the error message "SkynetMaxUploadSize header is missing" in changing from 4.1 to 4.3 "uploadFile" and "uploadLargeFile" to "skynet-js", and then changing it to "skynet-nodejs version".**

**Sorry for the huge text.
I hope you understand everything.**

**Comment by m-cat** [comment]
Not sure I understand... are you saying it works with skynet-js 4.3 but not 4.1? We changed the algorithm a lot in 4.3, which may account for it. But the team is already working on a fix for the header issue on our servers - sounds like they know what happened and just need a couple days to deploy a fix. 

In the meantime I can run my own tests and port the new algorithm to nodejs.

**Comment by parajbs** [comment]
Hello **m-cat,**

**Sorry again**, I did about 60 tests yesterday and always just attached the results and my thoughts before posting anything.

**The problem seems to be solved. Thanks to all.**

I can again upload a file larger than 41MB via the "https://siasky.net" portal.
It works in the browser with "skynet-js" and also in "skynet-nodejs".
Everything is going great and there are no more error messages.

**Comment by m-cat** [comment]
Awesome @parajbs ! Thanks for bringing this to our attention!
