### ISSUE TITLE
Remove encryption module from nodejs-skynet

### ISSUE THREAD

**Issue by MSevey** [SkynetLabs/nodejs-skynet#191]
This module includes the skykeys stuff that ended up not being relevant to Skynet at all. It's merely an artifact from the earliest of the days of this SDK.

**Comment by parajbs** [comment]
Hello MSevey,

Here's the PR: https://github.com/SkynetLabs/nodejs-skynet/pull/194
You can control it and give info.

**Comment by kwypchlo** [comment]
removed in https://github.com/SkynetLabs/nodejs-skynet/pull/194
