### ISSUE TITLE
Parallel large uploads in nodejs

### ISSUE THREAD

**Issue by MSevey** [SkynetLabs/nodejs-skynet#192]
Note: currently not supported in Node.

https://github.com/tus/tus-js-client/issues/303

**Comment by parajbs** [comment]
Hello **MSevey,**

I looked at the code in "skynet-js" and compared it with "nodejs-skynet".
**Yes, it is not supported at the moment.**

There is **some code to port from "skynet-js" to "nodejs-skynet"** to make it work.

I can first create a new PR, where I port all the necessary functions that you bring to it.

After that m-cat or I can create another RP for the new features of tus integrated in "skynet-js" to port to "nodejs-skynet".

**Comment by parajbs** [comment]
Hello MSevey,

Sorry again, you can of course also create the RP or program it.
I didn't mean to exclude you. sorry
Sometimes I'm too quick to dismiss the comments.

**Comment by kwypchlo** [comment]
functionality integrated in https://github.com/SkynetLabs/nodejs-skynet/pull/195
