### ISSUE TITLE
integration "scripts/deploy.js" and "scripts/get_servers.ts" from "SkynetLabs/skynet-js"

### ISSUE THREAD

**Issue by parajbs** [SkynetLabs/nodejs-skynet#199]
Hello **@kwypchlo, @MSevey and skynet team,**

I would like to port the two scripts "scripts/deploy.js" and "scripts/get_servers.ts" from "SkynetLabs/skynet-js" to "SkynetLabs/nodejs-skynet".

I also modified "get_servers.js" a little bit so that you can use commandline arguments "--dev" / "--free" / "--pro" and "--custom=" to better filter a list of servers can.

For the "Portal_Server_List" I took the list from the "SkynetLabs/siasky-tools" repo and uploaded it to skynet.

**If you want, can I change the script so that you can load "Portal_Server_List" as a ".json" file from the folder?**

Since the script "scripts/deploy.js" is already javascript, we only need to include it unchanged in "SkynetLabs/nodejs-skynet". I can't test it because I don't have an hns domain. You should just test again if you want.

**Can I finish a new RP, or should I wait until we finish this RP ( https://github.com/SkynetLabs/nodejs-skynet/pull/195 )?**

**Comment by parajbs** [comment]
**Hello @kwypchlo,**

I made a really nice "scripts/get_servers.js" for "SkynetLabs/nodejs-skynet" from "scripts/get_servers.ts" from "SkynetLabs/skynet-js".
Could be very helpful.

**I'm ready to push** it in a new RP **but will wait until this one ( https://github.com/SkynetLabs/nodejs-skynet/issues/195 ) is ready.**

**Comment by kwypchlo** [comment]
Hello @parajbs! Thank you for coming up with the pull request however as I explained in https://github.com/SkynetLabs/nodejs-skynet/pull/202#issuecomment-1279542444 those script should not get ported to this repository.
