### ISSUE TITLE
Skynet nodejs sdk does not work in react app out of the box

### ISSUE THREAD

**Issue by Dygnify** [SkynetLabs/nodejs-skynet#201]
## Describe the bug
Skynet nodejs sdk does not work in react app out of the box

## To Reproduce
1. Create a sample react app
2. install Skynet nodejs sdk package 
3. try to follow documenttion for file upload and download

## Actual behavior
application failed to build as it cannot find references for fs and path
## Expected behavior
App should build without any errors

**Comment by kwypchlo** [comment]
This sdk is designed to work with Node.js environment. For browser environment usage please refer to https://www.npmjs.com/package/skynet-js instead.

**Comment by Dygnify** [comment]
Thanks for the clarification and quick reply
